language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.0
script:
- set -o pipefail
- travis_retry xcodebuild -workspace Example/ToastFancy.xcworkspace -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
