# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.2
script:
 - xcodebuild -scheme ToastFancy -sdk iphonesimulator build
